name: insightmind_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  pdf: ^3.10.8
  share_plus: ^9.0.0
  printing: ^5.11.1
  percent_indicator: ^4.2.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  uuid: ^4.4.0
  camera: ^0.11.0+1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  fl_chart: ^1.1.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  freezed: ^2.5.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true
  assets:
    - assets/images/